name: leads_in
description: Leads IN Flutter App

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  flutter_svg: ^0.18.1
  animations: ^1.1.2
  flutter_form_builder: ^3.13.3
  intl: ^0.16.1
  pin_code_fields: ^5.0.1
  sliding_up_panel: ^1.0.2
  expandable_bottom_sheet: ^0.2.1+1
  circular_profile_avatar: ^1.0.6
  percent_indicator: ^2.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins_thin.ttf
          weight: 100
        - asset: assets/fonts/poppins_thin_italic.ttf
          weight: 100
          style: italic

        - asset: assets/fonts/poppins_extra_light.ttf
          weight: 200
        - asset: assets/fonts/poppins_extra_light_italic.ttf
          weight: 200
          style: italic

        - asset: assets/fonts/poppins_light.ttf
          weight: 300
        - asset: assets/fonts/poppins_light_italic.ttf
          weight: 300
          style: italic

        - asset: assets/fonts/poppins_regular.ttf
        - asset: assets/fonts/poppins_italic.ttf
          style: italic

        - asset: assets/fonts/poppins_medium.ttf
          weight: 500
        - asset: assets/fonts/poppins_medium_italic.ttf
          weight: 500
          style: italic

        - asset: assets/fonts/poppins_semi_bold.ttf
          weight: 600
        - asset: assets/fonts/poppins_semi_bold_italic.ttf
          weight: 600
          style: italic

        - asset: assets/fonts/poppins_bold.ttf
          weight: 700
        - asset: assets/fonts/poppins_bold_italic.ttf
          weight: 700
          style: italic

        - asset: assets/fonts/poppins_extra_bold.ttf
          weight: 800
        - asset: assets/fonts/poppins_extra_bold_italic.ttf
          weight: 800
          style: italic

        - asset: assets/fonts/poppins_black.ttf
          weight: 900
        - asset: assets/fonts/poppins_black_italic.ttf
          weight: 900
          style: italic

    - family: CenturyGothicRegular
      fonts:
        - asset: assets/fonts/CenturyGothicRegular.ttf
